data_preparation:
  train_test_ratio: 0.8
  train_val_ratio: 0.9
  random_state: 42
linear_regression:
  model_name: 'LinearRegression'
decision_tree:
  DecisionTree:
    max_depth: [ 2, 4, 6, 7 ]
    splitter: [ 'best', 'random' ]
    min_samples_split: [ 2, 3, 4 ]
    min_samples_leaf: [ 1, 2, 3, 4 ]
  RandomForest:
    n_estimators: [1, 2, 5, 10, 15]
    max_depth: [ 2, 4, 6, 7 ]
    min_samples_split: [ 2, 3, 4, 6, 7 ]
    min_samples_leaf: [ 1, 2, 3, 4 ]
  ExtraTree:
    n_estimators: [1, 2, 5, 10, 15]
    max_depth: [ 2, 4, 6, 7 ]
    min_samples_split: [ 2, 3, 4, 10, 15 ]
    min_samples_leaf: [ 1, 2, 3, 4, 18, 48 ]
catboost:
  CatBoost: # если брать больше, то компьютер взрывается [у меня]
    iterations: [150] # 150
    depth: [10] # 6
    learning_rate: [0.1] # 0.1
    l2_leaf_reg: [5]  # 1
    loss_function: [ 'RMSE' ] # стандарт - Root Mean Squared Error
    verbose: [ False ]
  CatBoost_Prod:
    iterations: 150
    depth: 6
    learning_rate: 0.05
    l2_leaf_reg: 3
    loss_function: 'RMSE'
    verbose: False