stages:
  data_preparation:
    cmd: python data_preparation.py -id data/raw -od data/prepared -uf data/raw/test_scores.csv
    deps:
      - data_preparation.py
      - data/raw
      - data/raw/test_scores.csv
    outs:
      - data/prepared
    params:
      - data_preparation
  linear_regression:
    cmd: python linear_regression.py -id data/prepared -od data/models -mn ${linear_regression.model_name}
    deps:
      - linear_regression.py
      - data/prepared
    outs:
      - data/models/${linear_regression.model_name}.csv
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression
  linear_regression_validation:
    cmd: python linear_regression_validation.py -id data/prepared/ -im data/models/${linear_regression.model_name}.joblib -mn ${linear_regression.model_name}
    deps:
      - linear_regression_validation.py
      - data/prepared/
      - data/models/${linear_regression.model_name}.joblib
    params:
      - linear_regression
  linear_regression_prod:
    cmd: python linear_regression_prod.py -id data/prepared/ -od data/models/ -mn ${linear_regression.model_name}
    deps:
      - linear_regression_prod.py
      - data/prepared
      - data/models/${linear_regression.model_name}.joblib
    outs:
      - data/models/${linear_regression.model_name}_prod.csv
      - data/models/${linear_regression.model_name}_prod.joblib
    params:
      - linear_regression
  decision_tree:
    foreach: ${decision_tree}
    do:
      cmd: python decision_tree.py -id data/prepared -od data/models -bm data/models/${linear_regression.model_name}_prod.joblib -mn ${key} -p params.yaml
      deps:
        - decision_tree.py
        - data/prepared
        - data/models/${linear_regression.model_name}_prod.joblib
      outs:
        - data/models/${key}.joblib
      params:
        - decision_tree
  decision_tree_validation:
    foreach: ${decision_tree}
    do:
      cmd: python decision_tree_validation.py -id data/prepared/ -im data/models/${key}.joblib -bm data/models/${linear_regression.model_name}_prod.joblib -mn ${key}
      deps:
        - decision_tree_validation.py
        - data/prepared/
        - data/models/${key}.joblib
        - data/models/${linear_regression.model_name}_prod.joblib
      params:
        - decision_tree
  decision_tree_prod:
    foreach: ${decision_tree}
    do:
      cmd: python decision_tree_prod.py -id data/prepared/ -od data/models/ -mn ${key}
      deps:
        - decision_tree_prod.py
        - data/prepared
        - data/models/${key}.joblib
      outs:
        - data/models/${key}_prod.joblib
      params:
        - decision_tree
  catboost:
    cmd: python catboost_dt.py -id data/prepared -od data/models -bm data/models/${linear_regression.model_name}_prod.joblib -mn CatBoost
    deps:
      - catboost_dt.py
      - data/prepared
      - data/models/${linear_regression.model_name}_prod.joblib
    outs:
      - data/models/CatBoost.joblib
    params:
      - catboost
  catboost_validation:
    cmd: python catboost_validation.py -id data/prepared/ -mp data/models/CatBoost.joblib -bm data/models/${linear_regression.model_name}_prod.joblib -mn CatBoost
    deps:
      - catboost_validation.py
      - data/prepared/
      - data/models/CatBoost.joblib
      - data/models/${linear_regression.model_name}_prod.joblib
    params:
      - catboost
  catboost_prod:
    cmd: python catboost_prod.py -id data/prepared/ -od data/models/ -mn CatBoost
    deps:
      - catboost_prod.py
      - data/prepared
    outs:
      - data/models/CatBoost_prod.joblib
    params:
      - catboost
  neural_network:
    cmd: python neural_network.py -id data/prepared -od data/models -mn ${neural_network.model_name} -lp data/logs -p params.yaml
    deps:
      - neural_network.py
      - data/prepared
    outs:
      - data/models/${neural_network.model_name}.joblib
    params:
      - neural_network
  neural_network_validation:
    cmd: python neural_network_validation.py -id data/prepared/ -im data/models/${neural_network.model_name}.joblib -mn ${neural_network.model_name} -lp data/logs -p params.yaml
    deps:
      - neural_network_validation.py
      - data/prepared/
      - data/models/${neural_network.model_name}.joblib
    params:
      - neural_network
  neural_network_prod:
    cmd: python neural_network_prod.py -id data/prepared/ -od data/models/ -mn ${neural_network.model_name} -lp data/logs -p params.yaml
    deps:
      - neural_network_prod.py
      - data/prepared
      - data/models/${neural_network.model_name}.joblib
    outs:
      - data/models/${neural_network.model_name}_prod.joblib
    params:
      - neural_network